// Test script for the Telegram bot API endpoints
const axios = require('axios');

// Configuration
const BASE_URL = 'http://localhost:3000';
const TEST_USER_ID = '123456789';

// Test token verification
async function testTokenVerification() {
    try {
        console.log('Testing token verification...');
        
        // This would normally be a valid token generated by the bot
        const response = await axios.post(`${BASE_URL}/verify-token`, {
            token: 'A1b2C3d4E5f6'
        });
        
        console.log('Token verification response:', response.data);
    } catch (error) {
        console.log('Token verification error:', error.response?.data || error.message);
    }
}

// Test access check
async function testAccessCheck() {
    try {
        console.log('Testing access check...');
        
        const response = await axios.post(`${BASE_URL}/check-access`, {
            userId: TEST_USER_ID
        });
        
        console.log('Access check response:', response.data);
    } catch (error) {
        console.log('Access check error:', error.response?.data || error.message);
    }
}

// Run tests
async function runTests() {
    console.log('Running API tests...\n');
    
    await testTokenVerification();
    console.log('');
    await testAccessCheck();
    
    console.log('\nTests completed.');
}

runTests();